package com.livrapp.api.delivery.domain;

public enum DeliveryStatus {
    DRAFT, PENDING_PAYMENT, PENDING, SCHEDULED, ASSIGNED, ACCEPTED,
    EN_ROUTE_PICKUP, AT_PICKUP, PICKED_UP, EN_ROUTE_DROPOFF, AT_DROPOFF,
    DELIVERED, DELIVERED_PENDING_SYNC, TENTATIVE_ECHOUEE, REASSIGNMENT_PENDING,
    AT_PARTNER, AT_AGENCY, RETURNED, ABANDONED, CANCELLED, EXPIRED, REFUNDED
}
